title: ""          # no title in header
description: ""    # no tagline/footer text
baseurl: "" 
url: "https://jayshar13.github.io"  # your site URL

theme: minima

# Build settings
markdown: kramdown

# Remove navbar links
header_pages: []

# Disable social/footer info
github_username: ""
linkedin: ""
email: ""
phone: ""

# Minima skin (keeps a clean look)
minima:
  skin: classic

