title: ""          # empty = no extra name in header
description: ""    # empty = no tagline in footer
baseurl: "" 
url: "https://jayshar13.github.io"

theme: minima

# Build settings
markdown: kramdown

# Social links (set blank if you don’t want them in footer)
github_username: ""
linkedin: ""
email: ""
phone: ""

# Minima skin
minima:
  skin: classic

